/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "OpenAIToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "main-vpc": {
      "type": "sst.aws.Vpc"
    }
    "mastra": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}